### ISSUE TITLE
Using Naming Service to find Analyzers

### ISSUE THREAD

**Issue by goern** [thoth-station/misc#1]
I have create an experiment to provide some kind of registry for analyser container images, so that we can get away from hard coded names and provide an index to users... later...

Example use case at 
https://github.com/thoth-station/misc/blob/d91763f344da39d38c75f2cd6616cce15b12cd67/radanalytics.py#L14

Naming Service at https://github.com/thoth-station/naming-service

**Comment by fridex** [comment]
> I have create an experiment to provide some kind of registry for analyser container images, so that we can get away from hard coded names and provide an index to users... later...

I think we will sooner or later need specific templates for different type of analyzers. Hardcoded templates for pods is no-go long term. For example templates to analyze stack on GPU enabled machines will have different configuration compared to pure CPU ones (request a node with a specific label that has GPU support).

I was thinking about encapsulating this logic into some querying mechanism that would tell us which containers should be spawned for different use cases and what openshift/k8s templates should be used for different runtime environment.
